version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/apache:/etc/apache2/sites-available
    depends_on:
      - db
    networks:
      - lamp-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: judge_scoring
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      test: ["CMD", "mysql", "-h", "localhost", "-u", "app_user", "-papp_password", "-e", "SELECT 1"]
      timeout: 10s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: tiger
    depends_on:
      - db
    networks:
      - lamp-network

volumes:
  mysql_data:

networks:
  lamp-network:
    driver: bridge
